application:
  info:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'

  api:
    path: '/api/v1/document-management'
  backend:
    errors:
      EMPLOYEE_NOT_SAVE:
        description: 'ErrorModel al guardar al empleado.'
        category: INTERNAL_ERROR
      EMPLOYEE_NOT_FOUND:
        description: 'Empleado no encontrado.'
        category: NOT_FOUND
      EMPLOYEE_NOT_UPDATE:
        description: 'ErrorModel al actualizar al empleado.'
        category: INTERNAL_ERROR

logging:
  file: document.log
  level:
    com.pe.relari: TRACE

server:
  port: 8106
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:document.db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: com.pe.relari.business.sqlite.config.database.SqLiteDialect
        format_sql: true